### PR TITLE
Fix Coupa instance creation

### LINKED ISSUE #465: Fix method for creating Coupa instances
The method counts now with `POST` method returning [CoupaInstance](https://github.com/gooddata/gooddata-java/blob/master/src/main/java/com/gooddata/connector/CoupaInstance.java) serialized JSON object. But in reality, it returns `URI` response with status `201 (Created)` containing URI address to created Coupa instance. We have to fix the method in this way.

### PR DESCRIPTION
**Pull request by peter-plochan**
Fixes #465

### CODE REVIEW

File: src/test/java/com/gooddata/connector/ConnectorServiceIT.java [hunk 1]
```diff
@@ -264,6 +271,24 @@ public void shouldFailCreatingCoupaInstance() throws Exception {
...
+                .havingPathEqualTo("/gdc/projects/PROJECT_ID/connectors/coupa/integration/config/settings/instances")
+             .respond()
+                .withStatus(201)
+                .withBody("{\"uri\":\"/coupa/instance/uri/123\"}");
+
+        onRequest()
+                .havingMethodEqualTo("GET")
+                .havingPathEqualTo("/coupa/instance/uri/123")
+             .respond()
+                .withStatus(404);
```
Comment (martiner) [inline src/test/java/com/gooddata/connector/ConnectorServiceIT.java]: why? this should be default
