### PR TITLE
fix: remove MeasureGroupHeader.totalItems

### LINKED ISSUE #549: MeasureGroupHeader has redundant totalItems
This can be never produced by API and doesn't make even sense.

### PR DESCRIPTION
**Pull request by jimirocks**
Resolves #549

### CODE REVIEW

File: src/main/java/com/gooddata/executeafm/response/AttributeHeader.java [hunk 1]
```diff
@@ -56,11 +60,11 @@ public AttributeHeader(@JsonProperty("name") final String name,
                            @JsonProperty("uri") final String uri,
                            @JsonProperty("identifier") final String identifier,
                            @JsonProperty("totalItems") final List<TotalHeaderItem> totalHeaderItems) {
-        super(totalHeaderItems);
         this.name = notEmpty(name, "name");
         this.localIdentifier = notEmpty(localIdentifier, "localIdentifier");
         this.uri = notEmpty(uri, "uri");
         this.identifier = notEmpty(identifier, "identifier");
+        this.totalItems = totalHeaderItems;
```
Comment (liry) [inline src/main/java/com/gooddata/executeafm/response/AttributeHeader.java]: is null valid value here?

Comment (jimirocks) [reply src/main/java/com/gooddata/executeafm/response/AttributeHeader.java]: yes it is
