### PR TITLE
send limited json for updating, no json for deleting S3 credentials

### LINKED ISSUE #503: acceptance tests fail at update and delete S3 credentials
The failure occurs due to sending the full `WarehouseS3Credentials` (with `links` and `updated`), whereas REST API only expects and allows three fields: `region`, `accessKey` and `secretKey`. Let's fix it so that only expected fields are sent in `PUT` request. As for `DELETE` request, request body should not be sent at all.

### PR DESCRIPTION
**Pull request by standevgd**
closes #503

### CODE REVIEW

File: src/main/java/com/gooddata/warehouse/WarehouseService.java [hunk 1]
```diff
@@ -546,27 +549,35 @@ public WarehouseS3Credentials getWarehouseS3Credentials(final Warehouse warehous
...
     private WarehouseTask createWarehouseTask(final String targetUri,
-                                              final WarehouseS3Credentials s3Credentials,
                                               final HttpMethod httpMethod,
+                                              final WarehouseS3Credentials s3Credentials,
                                               final Object... args) {
-        final HttpEntity<WarehouseTask> taskHttpEntity;
+        final MappingJacksonValue jacksonValue = new MappingJacksonValue(s3Credentials);
+        jacksonValue.setSerializationView(WarehouseS3Credentials.UpdateView.class);
+
+        final HttpEntity<MappingJacksonValue> requestEntity = (httpMethod == HttpMethod.DELETE)
```
Comment (ostumpf) [inline src/main/java/com/gooddata/warehouse/WarehouseService.java]: This method seems to behave quite differently for DELETE - I suggest not to use the same private method as PUT and POST.

File: src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+    @Mock
+    private Warehouse warehouse;
+    @Mock
+    private RestTemplate restTemplate;
+
+
+    @BeforeMethod
+    public void setUp() throws Exception {
+        MockitoAnnotations.initMocks(this);
```
Comment (ostumpf) [inline src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java]: I suggest to use `MockitoJUnitRunner` instead.

File: src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    private WarehouseService service;
+
+    private WarehouseS3Credentials s3Credentials = new WarehouseS3Credentials("region", "accessKey", "secretKey");
+
+    @Mock
+    private Warehouse warehouse;
+    @Mock
+    private RestTemplate restTemplate;
+
+
```
Comment (ostumpf) [inline src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java]: Extra line

File: src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+    @BeforeMethod
+    public void setUp() throws Exception {
+        MockitoAnnotations.initMocks(this);
+        service = new WarehouseService(restTemplate);
+        final ClientHttpResponse response = mock(ClientHttpResponse.class);
```
Comment (ostumpf) [inline src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java]: With `MockitoJUnitRunner`, you can use the `@Mock` annotation.

File: src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java (hunk 3 above)
Comment (standevgd) [reply src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java]: removed, added another unit test instead of it

File: src/main/java/com/gooddata/warehouse/WarehouseService.java (hunk 1 above)
Comment (standevgd) [reply src/main/java/com/gooddata/warehouse/WarehouseService.java]: extracted separate `createAdd/Update/DeleteTask` methods with different sets of arguments

**Comment by ostumpf** [comment]
LGTM

File: src/test/resources/warehouse/s3Credentials-update.json [hunk 5]
```diff
@@ -0,0 +1 @@
+{"s3Credentials":{"region":"region","accessKey":"accessKey","secretKey":"secretKey"}}
```
Comment (martiner) [inline src/test/resources/warehouse/s3Credentials-update.json]: this file duplicates s3Credentials-create.json - is that intentional

**Comment by martiner** [comment]
pls add test for UpdateView. in WarehouseS3CredentialsTest to test flow: object with links is serialized using this view without links

File: src/main/java/com/gooddata/warehouse/WarehouseService.java [hunk 6]
```diff
@@ -546,27 +549,52 @@ public WarehouseS3Credentials getWarehouseS3Credentials(final Warehouse warehous
         notNull(s3Credentials, "s3Credentials");
         notNull(s3Credentials.getUri(), "s3Credentials.links.self");
 
-        final WarehouseTask task = createWarehouseTask(s3Credentials.getUri(), s3Credentials, HttpMethod.DELETE);
+        final WarehouseTask task = createDeleteCredentialsTask(s3Credentials.getUri(), s3Credentials);
         return new PollResult<>(this, createS3PollHandler(s3Credentials.getUri(), task, Void.class, "delete"));
     }
 
+    private WarehouseTask createAddCredentialsTask(final String targetUri,
```
Comment (martiner) [inline src/main/java/com/gooddata/warehouse/WarehouseService.java]: inline the method as it has only a single usage

File: src/main/java/com/gooddata/warehouse/WarehouseService.java [hunk 7]
```diff
@@ -546,27 +549,52 @@ public WarehouseS3Credentials getWarehouseS3Credentials(final Warehouse warehous
...
+                                                   final WarehouseS3Credentials s3Credentials,
+                                                   final String warehouseId) {
+        return createWarehouseTask(targetUri, HttpMethod.POST, s3Credentials, createUpdateHttpEntity(s3Credentials), warehouseId);
+    }
+
+    private WarehouseTask createUpdateCredentialsTask(final String targetUri,
```
Comment (martiner) [inline src/main/java/com/gooddata/warehouse/WarehouseService.java]: inline

File: src/main/java/com/gooddata/warehouse/WarehouseService.java [hunk 8]
```diff
@@ -546,27 +549,52 @@ public WarehouseS3Credentials getWarehouseS3Credentials(final Warehouse warehous
...
+                                                      final WarehouseS3Credentials s3Credentials) {
+        return createWarehouseTask(targetUri, HttpMethod.PUT, s3Credentials, createUpdateHttpEntity(s3Credentials));
+    }
+
+    private WarehouseTask createDeleteCredentialsTask(final String targetUri,
```
Comment (martiner) [inline src/main/java/com/gooddata/warehouse/WarehouseService.java]: inline

File: src/test/resources/warehouse/s3Credentials-update.json (hunk 5 above)
Comment (standevgd) [reply src/test/resources/warehouse/s3Credentials-update.json]: got rid of duplication by having a modified `secretKey` in update request.

File: src/main/java/com/gooddata/warehouse/WarehouseService.java (hunk 6 above)
Comment (standevgd) [reply src/main/java/com/gooddata/warehouse/WarehouseService.java]: done

File: src/main/java/com/gooddata/warehouse/WarehouseService.java (hunk 7 above)
Comment (standevgd) [reply src/main/java/com/gooddata/warehouse/WarehouseService.java]: done

File: src/main/java/com/gooddata/warehouse/WarehouseService.java (hunk 8 above)
Comment (standevgd) [reply src/main/java/com/gooddata/warehouse/WarehouseService.java]: done

**Comment by standevgd** [comment]
@martiner `serializeUsingUpdateView()` test added, however instead of `MappingJacksonValue` I had to use `ObjectMapper` to test serialization with `UpdateView`.
